### PR TITLE
fix: validate email only when entering by user

### PR DESCRIPTION
**Pull request by polyen**

### CODE REVIEW

**Review by TrickyOldFox — COMMENTED** [review]
Why would we have an invalid email that comes from some other place then user ? We should never save it in DB if it's invalid ?

**Comment by polyen** [comment]
> Why would we have an invalid email that comes from some other place then user ? We should never save it in DB if it's invalid ?

The issue is that the class tries to validate email from DB. Since email is an optional field validation fails for empty emails (None)

**Comment by TrickyOldFox** [comment]
It feels like it's better to handle this when reading from the DB instead. The None is already a value that signals that field wasn't intialized and it's not a valid value for the Email class. So it would make sense to just have a .email attribute to be None instead of instance of an Email with value None

**Comment by polyen** [comment]
> It feels like it's better to handle this when reading from the DB instead. The None is already a value that signals that field wasn't intialized and it's not a valid value for the Email class. So it would make sense to just have a .email attribute to be None instead of instance of an Email with value None

I will disagree. It will break consistency. e.g. search looks for record.[field].value Additional checks will reduce abstraction in general. So imho abstraction gives more profit then None instead of empty class

**Pull request merged**
